
//The {adjective} {adjective} {noun} {verbed} {adverb} the {adjective} {noun}.

//Random Word Data Object
const words = {
    adjectives: ['adorable', 'adventurous', 'aggressive', 'agreeable', 'alert', 'alive', 'amused', 'angry', 'annoyed', 'annoying', 'anxious', 'arrogant', 'ashamed', 'attractive', 'average', 'awful', 'bad', 'beautiful', 'better', 'bewildered', 'black', 'bloody', 'blue', 'blue-eyed', 'blushing', 'bored', 'brainy', 'brave', 'breakable', 'bright', 'busy', 'calm', 'careful', 'cautious', 'charming', 'cheerful', 'clean', 'clear', 'clever', 'cloudy', 'clumsy', 'colorful', 'combative', 'comfortable', 'concerned', 'condemned', 'confused', 'cooperative', 'courageous', 'crazy', 'creepy', 'crowded', 'cruel', 'curious', 'cute', 'dangerous', 'dark', 'dead', 'defeated', 'defiant', 'delightful', 'depressed', 'determined', 'different', 'difficult', 'disgusted', 'distinct', 'disturbed', 'dizzy', 'doubtful', 'drab', 'dull', 'eager', 'easy', 'elated', 'elegant', 'embarrassed', 'enchanting', 'encouraging', 'energetic', 'enthusiastic', 'envious', 'evil', 'excited', 'expensive', 'exuberant', 'fair', 'faithful', 'famous', 'fancy', 'fantastic', 'fierce', 'filthy', 'fine', 'foolish', 'fragile', 'frail', 'frantic', 'friendly', 'frightened', 'funny', 'gentle', 'gifted', 'glamorous', 'gleaming', 'glorious', 'good', 'gorgeous', 'graceful', 'grieving', 'grotesque', 'grumpy', 'handsome', 'happy', 'healthy', 'helpful', 'helpless', 'hilarious', 'homeless', 'homely', 'horrible', 'hungry', 'hurt', 'ill', 'important', 'impossible', 'inexpensive', 'innocent', 'inquisitive', 'itchy', 'jealous', 'jittery', 'jolly', 'joyous', 'kind', 'lazy', 'light', 'lively', 'lonely', 'long', 'lovely', 'lucky', 'magnificent', 'misty', 'modern', 'motionless', 'muddy', 'mushy', 'mysterious', 'nasty', 'naughty', 'nervous', 'nice', 'nutty', 'obedient', 'obnoxious', 'odd', 'old-fashioned', 'open', 'outrageous', 'outstanding', 'panicky', 'perfect', 'plain', 'pleasant', 'poised', 'poor', 'powerful', 'precious', 'prickly', 'proud', 'putrid', 'puzzled', 'quaint', 'real', 'relieved', 'repulsive', 'rich', 'scary', 'selfish', 'shiny', 'shy', 'silly', 'sleepy', 'smiling', 'smoggy', 'sore', 'sparkling', 'splendid', 'spotless', 'stormy', 'strange', 'stupid', 'successful', 'super', 'talented', 'tame', 'tasty', 'tender', 'tense', 'terrible', 'thankful', 'thoughtful', 'thoughtless', 'tired', 'tough', 'troubled', 'ugliest', 'ugly', 'uninterested', 'unsightly', 'unusual', 'upset', 'uptight', 'vast', 'victorious', 'vivacious', 'wandering', 'weary', 'wicked', 'wide-eyed', 'wild', 'witty', 'worried', 'worrisome', 'wrong', 'zany', 'zealous'],
    nouns: ['mother', 'father', 'baby', 'child', 'toddler', 'teenager', 'grandmother', 'student', 'teacher', 'minister', 'businessperson', 'salesclerk', 'woman', 'man', 'Air', 'Ant', 'Apartment', 'Arrow', 'Baby', 'Baby', 'Backyard', 'Bag', 'Ball', 'Bar', 'Barbie', 'Basket', 'Bat', 'Bell', 'Belt', 'Bicycle', 'Bike', 'Birds', 'Biscuit', 'Blackboard', 'Blade', 'Book', 'Bookcases', 'Box', 'Bridge', 'Brush', 'Bucket', 'Bulb', 'Bus', 'Buttons', 'Cable', 'Camera', 'Cane', 'Cap', 'Car', 'Carpet', 'Cat', 'Cave', 'Cement', 'Chair', 'Chips', 'Chocolate', 'City', 'Clip', 'Clothes', 'Cloud', 'Coconut', 'Coffee', 'Coin', 'Color', 'Comb', 'Cookware', 'Corn', 'Cup', 'Cupboard', 'Currency', 'Cylinder', 'Dates', 'Desk', 'Dining table', 'Dog', 'Dresser', 'Drink', 'Dust', 'Eagle', 'Earth', 'Elephant', 'Eraser', 'Fan', 'Fire', 'Flowers', 'Food', 'Forest', 'Fridge', 'Frog', 'Gadgets', 'Garden', 'Gas', 'Gel', 'Glass', 'Hair', 'Hammer', 'Hand', 'Hockey', 'House', 'Ice', 'Icecream', 'Iron', 'Jug', 'Key', 'Keyboard', 'Kit', 'Kite', 'Knife', 'Lamp', 'Laptop', 'Leather', 'Leaves', 'Lemon', 'Lift', 'Light', 'Lock', 'Mall', 'Mango', 'Mars', 'Medicine', 'Milk', 'Mirror', 'Mobile', 'Monitor', 'Moon', 'Motor', 'Mountain', 'Mouse', 'Nose', 'Notebook', 'Ocean', 'Oil', 'Paint', 'Paint', 'Paint', 'Paper', 'Paper', 'Park', 'Peanut', 'Pen', 'Pencil', 'Perfume', 'Phone', 'Pizza', 'Planet', 'Plant', 'Plastic', 'Plates', 'Police', 'Potato', 'Restaurant', 'Rice', 'Ring', 'River', 'Road', 'Rope', 'Rubber', 'Salt', 'Sand', 'Saw', 'School', 'Sea', 'Shampoo', 'Shoes', 'Shoes', 'Shop', 'Shop', 'Shopner', 'Shower', 'Soap', 'Soil', 'Spider', 'Spoon', 'Stair', 'Station', 'Stem', 'Sugar', 'Sun', 'Sweet', 'Table', 'Tap', 'Taxi', 'Tea', 'Tea', 'Teeth', 'Television', 'Tennis', 'clock', 'door', 'Thread', 'Tiger', 'Tomato', 'Tools', 'Toothbrush', 'Toothpaste', 'Towel', 'Toy', 'Train', 'Train airplane', 'Tree', 'Tree', 'Truck', 'Van', 'Vegetable', 'Wall', 'Wallet', 'Watch', 'Water', 'Wheat', 'Window', 'Winter', 'Wire', 'Wood', 'Zoo'],
    verbs: []
}

const randomAdjective = words.adjectives[Math.floor(Math.random() * words.adjectives.length)];
const randomNoun = words.nouns[Math.floor(Math.random() * words.nouns.length)].toLowerCase();
console.log('Random adjective: '+randomAdjective);
console.log('Random noun: '+randomNoun);
console.log('Adjectives: '+words.adjectives.length);
console.log('Nouns: '+words.nouns.length);


